### ISSUE TITLE
v2.4.22 broken with SSR: true

### ISSUE THREAD

**Issue by CharlesBT** [harlan-zw/nuxt-simple-sitemap#45]
### Describe the bug

I have sitemap.xml return error 500 on SSR:true (working well with SSR:false).

I had to go back to previous version v2.4.21 to get it working on SSR true

**Comment by harlan-zw** [comment]
Would you mind sharing the stack trace or a reproduction?

**Comment by CharlesBT** [comment]
Hi same issue with 2.4.23, this is what i've got :
[nuxt] [request error] [unhandled] [500] terminated
  at Fetch.onAborted (node:internal/deps/undici/undici:11323:53)  
  at Fetch.emit (node:events:513:28)  
  at Fetch.terminate (node:internal/deps/undici/undici:10578:14)  
  at Object.onError (node:internal/deps/undici/undici:11418:36)  
  at Request.onError (node:internal/deps/undici/undici:8210:31)  
  at errorRequest (node:internal/deps/undici/undici:10264:17)  
  at TLSSocket.onSocketClose (node:internal/deps/undici/undici:9710:9)  
  at TLSSocket.emit (node:events:525:35)  
  at node:net:322:12  
  at TCP.done (node:_tls_wrap:588:7)
[Vue warn]: A plugin must either be a function or an object with an "install" function.
[intlify] Not found 'terminated' key in 'en' locale messages.

**Comment by harlan-zw** [comment]
Can you share some of your code, ideally a reproduction? I can't debug your issue with limited information

**Comment by harlan-zw** [comment]
Hey @fenixrhiulta, the code related to this is the automatic image discovery. I've pushed up a fix in 2.4.24.

**Comment by fenixrhiulta** [comment]
Hello @harlan-zw, thanks for your help.

I still have the same problem on v2.4.24 and v2.5.0. Occurs only with ssr true.

**Comment by CharlesBT** [comment]
I tested 2.5.0 same issue with SSR true

**Comment by harlan-zw** [comment]
> Hello @harlan-zw, thanks for your help.
> 
> I still have the same problem on v2.4.24 and v2.5.0. Occurs only with ssr true.

Can you try disabling the image discovery?

```ts
export default defineNuxtConfig({
  sitemap: {
    discoverImages: false
  }
})
```

**Comment by CharlesBT** [comment]
> > Hello @harlan-zw, thanks for your help.
> > I still have the same problem on v2.4.24 and v2.5.0. Occurs only with ssr true.
> 
> Can you try disabling the image discovery?
> 
> ```ts
> export default defineNuxtConfig({
>   sitemap: {
>     discoverImages: false
>   }
> })
> ```

discoverImages: false solved the issue for me with 2.5.0 > thanks !

**Comment by fenixrhiulta** [comment]
> > Hello @harlan-zw, thanks for your help.
> > I still have the same problem on v2.4.24 and v2.5.0. Occurs only with ssr true.
> 
> Can you try disabling the image discovery?
> 
> ```ts
> export default defineNuxtConfig({
>   sitemap: {
>     discoverImages: false
>   }
> })
> ```

It's works for me, thanks!

**Comment by harlan-zw** [comment]
Sorry @CharlesBT, I think your issue is separate to @fenixrhiulta's.

I'm happy to try and help you but I need more information

**Comment by harlan-zw** [comment]
Sorry @CharlesBT, I think your issue is separate to @fenixrhiulta's.

I'm happy to try and help you but I need more information

**Comment by CharlesBT** [comment]
v2.6.0 fixed the issue
